version: '3'

services:
  backend:
    build:
      context: flask_backend
    image: jitsi/flask-backend
    environment:
      - ENVIRONMENT=DEV
    ports:
      - 5000:5000
    volumes:
      - .:/app
    healthcheck:
      test: curl --fail http://127.0.0.1:5000/